<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Way2Automation-TESTING" duration-ms="68459" started-at="2017-11-05T01:13:49Z" finished-at="2017-11-05T01:14:58Z">
    <groups>
    </groups>
    <test name="way2Automation" duration-ms="68459" started-at="2017-11-05T01:13:49Z" finished-at="2017-11-05T01:14:58Z">
      <class name="com.pack.common.test.InteractionDemo">
        <test-method status="PASS" signature="TestBaseSetupStart(java.lang.String, java.lang.String)[pri:0, instance:com.pack.common.test.InteractionDemo@4c70fda8]" name="TestBaseSetupStart" is-config="true" duration-ms="38535" started-at="2017-11-04T18:13:49Z" finished-at="2017-11-04T18:14:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://way2automation.com/way2auto_jquery/index.php]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestBaseSetupStart -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.pack.common.test.InteractionDemo@4c70fda8]" name="setUp" is-config="true" duration-ms="1" started-at="2017-11-04T18:14:28Z" finished-at="2017-11-04T18:14:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="clckSortable()[pri:0, instance:com.pack.common.test.InteractionDemo@4c70fda8]" name="clckSortable" duration-ms="29753" started-at="2017-11-04T18:14:28Z" finished-at="2017-11-04T18:14:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Item 5] but found [Item 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Item 5] but found [Item 1]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.pack.common.packageObjects.BasePage.testSortableFunctionality(BasePage.java:186)
	at com.pack.common.test.InteractionDemo.clckSortable(InteractionDemo.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clckSortable -->
      </class> <!-- com.pack.common.test.InteractionDemo -->
    </test> <!-- way2Automation -->
  </suite> <!-- Way2Automation-TESTING -->
</testng-results>
